// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAddkZnwVwBr00t91Q_gVa5cqHTQPjaCFw',
    appId: '1:872175185384:android:17e1b994e1bab9f325885d',
    messagingSenderId: '872175185384',
    projectId: 'word-master-cda97',
    storageBucket: 'word-master-cda97.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTgakZFmDn1w9NeerAa7uUT21A2ZN4myg',
    appId: '1:872175185384:web:52a4c326773dfb2225885d',
    messagingSenderId: '872175185384',
    projectId: 'word-master-cda97',
    authDomain: 'word-master-cda97.firebaseapp.com',
    storageBucket: 'word-master-cda97.firebasestorage.app',
    measurementId: 'G-QKP8NXYR0Y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjy9-7lx90JO6RsE_et79gcI16ZFuQGG0',
    appId: '1:872175185384:ios:4123ecbc2fe8617525885d',
    messagingSenderId: '872175185384',
    projectId: 'word-master-cda97',
    storageBucket: 'word-master-cda97.firebasestorage.app',
    iosBundleId: 'com.example.worldeMobile',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjy9-7lx90JO6RsE_et79gcI16ZFuQGG0',
    appId: '1:872175185384:ios:4123ecbc2fe8617525885d',
    messagingSenderId: '872175185384',
    projectId: 'word-master-cda97',
    storageBucket: 'word-master-cda97.firebasestorage.app',
    iosBundleId: 'com.example.worldeMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTgakZFmDn1w9NeerAa7uUT21A2ZN4myg',
    appId: '1:872175185384:web:2d8b4002c30edd7525885d',
    messagingSenderId: '872175185384',
    projectId: 'word-master-cda97',
    authDomain: 'word-master-cda97.firebaseapp.com',
    storageBucket: 'word-master-cda97.firebasestorage.app',
    measurementId: 'G-L80G82RPGV',
  );

}